package velkonost.technical.analysis.indicator.base

enum class IndicatorName(val title: String) {

    // Volume
    Adi("volume_adi"),
    Obv("volume_obv"),
    Cmf("volume_cmf"),
    Fi("volume_fi"),
    Em("volume_em"),
    SmaEm("volume_sma_em"),
    Vpt("volume_vpt"),
    Vwap("volume_vwap"),
    Mfi("volume_mfi"),
    Nvi("volume_nvi"),

    // Volatility
    Bbm("volatility_bbm"),
    Bbh("volatility_bbh"),
    Bbl("volatility_bbl"),
    Bbw("volatility_bbw"),
    Bbp("volatility_bbp"),
    Bbhi("volatility_bbhi"),
    Bbli("volatility_bbli"),
    Kcc("volatility_kcc"),
    Kch("volatility_kch"),
    Kcl("volatility_kcl"),
    Kcw("volatility_kcw"),
    Kcp("volatility_kcp"),
    Kchi("volatility_kchi"),
    Kcli("volatility_kcli"),
    Dcl("volatility_dcl"),
    Dch("volatility_dch"),
    Dcm("volatility_dcm"),
    Dcw("volatility_dcw"),
    Dcp("volatility_dcp"),
    Atr("volatility_atr"),
    Ui("volatility_ui"),

    // Trend
    Macd("trend_macd"),
    MacdSignal("trend_macd_signal"),
    MacdDiff("trend_macd_diff"),
    SmaFast("trend_sma_fast"),
    SmaSlow("trend_sma_slow"),
    EmaFast("trend_ema_fast"),
    EmaSlow("trend_ema_slow"),
    VortexIndPositive("trend_vortex_ind_pos"),
    VortexIndNegative("trend_vortex_ind_neg"),
    VortexIndDiff("trend_vortex_ind_diff"),
    Trix("trend_trix"),
    MassIndex("trend_mass_index"),
    Dpo("trend_dpo"),
    Kst("trend_kst"),
    KstSignal("trend_kst_sig"),
    KstDiff("trend_kst_diff"),
    IchimokuConv("trend_ichimoku_conv"),
    IchimokuBase("trend_ichimoku_base"),
    IchimokuA("trend_ichimoku_a"),
    IchimokuB("trend_ichimoku_b"),
    Stc("trend_stc"),
    IchimokuVisualA("trend_visual_ichimoku_a"),
    IchimokuVisualB("trend_visual_ichimoku_b"),
    AroonUp("trend_aroon_up"),
    AroonDown("trend_aroon_down"),
    AroonIndicator("trend_aroon_ind"),

    // Momentum
    Rsi("momentum_rsi"),
    StochRsi("momentum_stoch_rsi"),
    StochRsiK("momentum_stoch_rsi_k"),
    StochRsiD("momentum_stoch_rsi_d"),
    Tsi("momentum_tsi"),
    Uo("momentum_uo"),
    Stoch("momentum_stoch"),
    StochSignal("momentum_stoch_signal"),
    Wr("momentum_wr"),
    Ao("momentum_ao"),
    Roc("momentum_roc"),
    Ppo("momentum_ppo"),
    PpoSignal("momentum_ppo_signal"),
    PpoHist("momentum_ppo_hist"),
    Pvo("momentum_pvo"),
    PvoSignal("momentum_pvo_signal"),
    PvoHist("momentum_pvo_hist"),
    Kama("momentum_kama"),

    // Other
    Dr("others_dr"),
    Dlr("others_dlr"),
    Cr("others_cr")

}