package velkonost.technical.analysis.strategy.base

/**
 * Base abstract class for all trading strategies in the technical analysis library.
 * A strategy combines one or more technical indicators to generate trading signals.
 * Each strategy must implement the calculate() method to determine its trading decision.
 *
 * Key concepts:
 * - Strategies use technical indicators as building blocks
 * - Each strategy implements a specific trading logic
 * - Strategies generate clear buy/sell/hold signals
 * - Strategies can be combined to create more complex trading systems
 *
 * Usage:
 * 1. Extend this class for new strategies
 * 2. Implement the calculate() method with your strategy's logic
 * 3. Use technical indicators to analyze market conditions
 * 4. Return a clear trading decision (StrategyDecision)
 *
 * Best practices:
 * - Keep strategies focused on a single trading concept
 * - Document the strategy's logic and assumptions
 * - Consider market conditions and risk management
 * - Test strategies thoroughly before live trading
 *
 * @property name The name of the strategy, defined in StrategyName enum
 * @property scale The decimal scale used for calculations (default: 10)
 */
abstract class Strategy(
    val name: StrategyName,
    protected val scale: Int = 10
) {
    /**
     * Abstract method that must be implemented by all strategies to generate trading signals.
     * This method should analyze the market conditions using technical indicators
     * and return a trading decision (buy, sell, or hold).
     *
     * The implementation should:
     * 1. Calculate required technical indicators
     * 2. Analyze market conditions based on indicator values
     * 3. Apply the strategy's specific rules and logic
     * 4. Generate a clear trading signal
     *
     * @return StrategyDecision representing the trading signal generated by the strategy
     */
    abstract fun calculate(): StrategyDecision
}