package velkonost.technical.analysis.strategy.base

/**
 * Enum class representing the possible trading decisions generated by strategies.
 * This enum is used to standardize the output of all trading strategies in the library,
 * providing clear and unambiguous trading signals.
 *
 * Available Decisions:
 * - Long: Indicates a buy signal, suggesting to enter a long position
 *   * Generated when strategy conditions favor upward price movement
 *   * Used for trend-following or reversal strategies
 *   * May be accompanied by specific entry conditions
 *
 * - Short: Indicates a sell signal, suggesting to enter a short position
 *   * Generated when strategy conditions favor downward price movement
 *   * Used for trend-following or reversal strategies
 *   * May be accompanied by specific entry conditions
 *
 * - Nothing: Indicates no trading signal, suggesting to stay out of the market
 *   * Generated when strategy conditions are unclear or unfavorable
 *   * Used to avoid trading in uncertain market conditions
 *   * Helps manage risk by preventing unnecessary trades
 *
 * Usage:
 * - Strategies return one of these decisions in their calculate() method
 * - Decisions can be used to generate trading signals
 * - Multiple strategies can be combined based on their decisions
 * - Decisions can be used for backtesting and performance analysis
 *
 * Best Practices:
 * - Use clear criteria for each decision type
 * - Consider market conditions when interpreting decisions
 * - Combine with risk management rules
 * - Validate decisions with additional analysis
 */
enum class StrategyDecision {
    Long,
    Short,
    Nothing
}